# Generated by Django 4.1 on 2022-08-20 17:46

from django.db import migrations
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='address',
            field=polls.models.PhysicalAddressField(blank=True),
        ),
    ]
